2024-04-01 18:15:00,964 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Configure stats pid to 4705
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/.config/wandb/settings
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/Downloads/assignment-4/wandb/settings
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:_log_setup():527] Logging user logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_181500-vvrjcc9r/logs/debug.log
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:_log_setup():528] Logging internal logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_181500-vvrjcc9r/logs/debug-internal.log
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x287b11540>
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:init():567] calling init triggers
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-01 18:15:00,965 INFO    MainThread:4705 [wandb_init.py:init():592] re-initializing run, found existing run on stack: 3gp8jlv0
2024-04-01 18:15:00,966 INFO    MainThread:4705 [wandb_run.py:_finish():2052] finishing run viditdpokharna/scene-recognition/3gp8jlv0
2024-04-01 18:15:00,966 INFO    MainThread:4705 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-01 18:15:00,967 INFO    MainThread:4705 [wandb_run.py:_restore():2275] restore
2024-04-01 18:15:00,967 INFO    MainThread:4705 [wandb_run.py:_restore():2281] restore done
2024-04-01 18:15:06,118 INFO    MainThread:4705 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-01 18:15:06,118 INFO    MainThread:4705 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-01 18:15:06,126 INFO    MainThread:4705 [wandb_run.py:_footer_sync_info():3879] logging synced files
2024-04-01 18:15:06,195 INFO    MainThread:4705 [wandb_init.py:init():617] starting backend
2024-04-01 18:15:06,195 INFO    MainThread:4705 [wandb_init.py:init():621] setting up manager
2024-04-01 18:15:06,199 INFO    MainThread:4705 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-01 18:15:06,199 INFO    MainThread:4705 [wandb_init.py:init():629] backend started and connected
2024-04-01 18:15:06,209 INFO    MainThread:4705 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-01 18:15:06,209 INFO    MainThread:4705 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-01 18:15:06,209 INFO    MainThread:4705 [wandb_init.py:init():721] updated telemetry
2024-04-01 18:15:06,211 INFO    MainThread:4705 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-01 18:15:07,466 INFO    MainThread:4705 [wandb_run.py:_on_init():2344] communicating current version
2024-04-01 18:15:07,685 INFO    MainThread:4705 [wandb_run.py:_on_init():2353] got version response 
2024-04-01 18:15:07,685 INFO    MainThread:4705 [wandb_init.py:init():805] starting run threads in backend
2024-04-01 18:15:10,185 INFO    MainThread:4705 [wandb_run.py:_console_start():2323] atexit reg
2024-04-01 18:15:10,185 INFO    MainThread:4705 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-01 18:15:10,185 INFO    MainThread:4705 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-01 18:15:10,185 INFO    MainThread:4705 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-01 18:15:10,185 INFO    MainThread:4705 [wandb_init.py:init():848] run started, returning control to user process
2024-04-01 18:16:12,885 INFO    MainThread:4705 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-01 18:16:12,885 INFO    MainThread:4705 [wandb_init.py:_pause_backend():438] pausing backend
2024-04-01 18:16:45,865 INFO    MainThread:4705 [wandb_init.py:_resume_backend():443] resuming backend
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Configure stats pid to 4705
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/.config/wandb/settings
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/Downloads/assignment-4/wandb/settings
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_init.py:_log_setup():527] Logging user logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_181645-njl0d3wu/logs/debug.log
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_init.py:_log_setup():528] Logging internal logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_181645-njl0d3wu/logs/debug-internal.log
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_init.py:init():567] calling init triggers
2024-04-01 18:16:45,884 INFO    MainThread:4705 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-01 18:16:45,885 INFO    MainThread:4705 [wandb_init.py:init():592] re-initializing run, found existing run on stack: vvrjcc9r
2024-04-01 18:16:45,886 INFO    MainThread:4705 [wandb_run.py:_finish():2052] finishing run viditdpokharna/scene-recognition/vvrjcc9r
2024-04-01 18:16:45,887 INFO    MainThread:4705 [jupyter.py:save_history():445] not saving jupyter history
2024-04-01 18:16:45,887 INFO    MainThread:4705 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-01 18:16:45,887 INFO    MainThread:4705 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-01 18:16:45,887 INFO    MainThread:4705 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-01 18:16:45,888 INFO    MainThread:4705 [wandb_run.py:_restore():2275] restore
2024-04-01 18:16:45,888 INFO    MainThread:4705 [wandb_run.py:_restore():2281] restore done
2024-04-01 18:16:48,877 INFO    MainThread:4705 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-01 18:16:48,877 INFO    MainThread:4705 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-01 18:16:48,880 INFO    MainThread:4705 [wandb_run.py:_footer_sync_info():3879] logging synced files
