2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Configure stats pid to 9285
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/.config/wandb/settings
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/Downloads/assignment-4/wandb/settings
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-01 22:11:10,120 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:_log_setup():527] Logging user logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_221110-zhhnbl03/logs/debug.log
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:_log_setup():528] Logging internal logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240401_221110-zhhnbl03/logs/debug-internal.log
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:_jupyter_setup():473] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x107db69e0>
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:init():567] calling init triggers
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:init():617] starting backend
2024-04-01 22:11:10,121 INFO    MainThread:9285 [wandb_init.py:init():621] setting up manager
2024-04-01 22:11:10,124 INFO    MainThread:9285 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-01 22:11:10,148 INFO    MainThread:9285 [wandb_init.py:init():629] backend started and connected
2024-04-01 22:11:10,156 INFO    MainThread:9285 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-01 22:11:10,156 INFO    MainThread:9285 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-01 22:11:10,156 INFO    MainThread:9285 [wandb_init.py:init():721] updated telemetry
2024-04-01 22:11:10,166 INFO    MainThread:9285 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-01 22:11:10,656 INFO    MainThread:9285 [wandb_run.py:_on_init():2344] communicating current version
2024-04-01 22:11:11,055 INFO    MainThread:9285 [wandb_run.py:_on_init():2353] got version response 
2024-04-01 22:11:11,055 INFO    MainThread:9285 [wandb_init.py:init():805] starting run threads in backend
2024-04-01 22:11:13,273 INFO    MainThread:9285 [wandb_run.py:_console_start():2323] atexit reg
2024-04-01 22:11:13,273 INFO    MainThread:9285 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-01 22:11:13,273 INFO    MainThread:9285 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-01 22:11:13,273 INFO    MainThread:9285 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-01 22:11:13,273 INFO    MainThread:9285 [wandb_init.py:init():848] run started, returning control to user process
2024-04-02 00:09:32,473 INFO    MainThread:9285 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-02 00:09:32,482 INFO    MainThread:9285 [wandb_init.py:_pause_backend():438] pausing backend
2024-04-02 00:15:42,379 INFO    MainThread:9285 [wandb_init.py:_resume_backend():443] resuming backend
2024-04-02 00:15:42,453 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-02 00:15:42,453 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Configure stats pid to 9285
2024-04-02 00:15:42,453 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/.config/wandb/settings
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from /Users/viditpokharna/Downloads/assignment-4/wandb/settings
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_init.py:_log_setup():527] Logging user logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240402_001542-pd032ofo/logs/debug.log
2024-04-02 00:15:42,454 INFO    MainThread:9285 [wandb_init.py:_log_setup():528] Logging internal logs to /Users/viditpokharna/Downloads/assignment-4/wandb/run-20240402_001542-pd032ofo/logs/debug-internal.log
2024-04-02 00:15:42,455 INFO    MainThread:9285 [wandb_init.py:init():567] calling init triggers
2024-04-02 00:15:42,455 INFO    MainThread:9285 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-02 00:15:42,455 INFO    MainThread:9285 [wandb_init.py:init():592] re-initializing run, found existing run on stack: zhhnbl03
2024-04-02 00:15:42,461 INFO    MainThread:9285 [wandb_run.py:_finish():2052] finishing run viditdpokharna/huggingface_scene_recognition/zhhnbl03
2024-04-02 00:15:42,462 INFO    MainThread:9285 [jupyter.py:save_history():445] not saving jupyter history
2024-04-02 00:15:42,463 INFO    MainThread:9285 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-02 00:15:42,463 INFO    MainThread:9285 [wandb_init.py:_jupyter_teardown():455] cleaning up jupyter logic
2024-04-02 00:15:42,463 INFO    MainThread:9285 [wandb_run.py:_atexit_cleanup():2292] got exitcode: 0
2024-04-02 00:15:42,464 INFO    MainThread:9285 [wandb_run.py:_restore():2275] restore
2024-04-02 00:15:42,465 INFO    MainThread:9285 [wandb_run.py:_restore():2281] restore done
2024-04-02 00:15:46,290 INFO    MainThread:9285 [wandb_run.py:_footer_history_summary_info():3920] rendering history
2024-04-02 00:15:46,292 INFO    MainThread:9285 [wandb_run.py:_footer_history_summary_info():3952] rendering summary
2024-04-02 00:15:46,304 INFO    MainThread:9285 [wandb_run.py:_footer_sync_info():3879] logging synced files
